name: GitHub Actions Demo
on: [push]
jobs:
  Setup:
    runs-on: ubuntu-latest
    steps:
      - run: |
          sudo curl -Lo /usr/bin/kind https://kind.sigs.k8s.io/dl/v0.10.0/kind-linux-amd64
  Test:
    needs: [Setup]
    runs-on: ubuntu-latest
    steps:
      - name: ðŸ§ª - Testing the software
        run: kind get clusters
      - name: dummy
        run: which kind
  Lint:
    needs: [Setup]
    runs-on: ubuntu-latest
    steps:
      - name: ðŸ‘• - Linting the software
        run: echo "It worked"
  Artifact:
    needs: [Test, Lint]
    runs-on: ubuntu-latest
    steps:
      - name: ðŸº - Dumb artifacts
        run: |
          mkdir output
          echo '{"a": true}' > output/dump.json
      - uses: actions/upload-artifact@v2
        with:
          name: dump.json
          path: output/dump.json

