name: GitHub Actions Demo
on: [push]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: engineerd/setup-kind@v0.5.0
      - name: ðŸ“¦ - Setting up K8s in Docker
        run: kind get clusters
  Test:
    needs: [Build]
    runs-on: ubuntu-latest
    steps:
      - name: ðŸ§ª - Testing the software
        run: kind get clusters
  Lint:
    needs: [Build]
    runs-on: ubuntu-latest
    steps:
      - name: ðŸ‘• - Linting the software
        run: echo "It worked"
  Artifact:
    needs: [Test, Lint]
    runs-on: ubuntu-latest
    steps:
      - name: ðŸº - Dumb artifacts
        run: |
          mkdir output
          echo '{"a": true}' > output/dump.json
        
